#!/bin/bash

source $(dirname $0)/helpers

TYPE=$( basename $0 )

RETVAL=0
for hook in $( find $( pwd )/.git/hooks/$TYPE.d -type f -o -type l ); do
  step "running <comment>$TYPE</comment> hook <comment>$( basename $hook )</comment>" $hook
  RESULT=$?
  if [ $RETVAL -eq 0 ]; then
    RETVAL=$RESULT
  fi
done

exit $RETVAL
